#!/bin/sh

# Set these paths appropriately

BIN=/home/lianet/expert/tools/tree-tagger-linux-3.2/bin
CMD=/home/lianet/expert/tools/tree-tagger-linux-3.2/cmd
LIB=/home/lianet/expert/tools/tree-tagger-linux-3.2/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
