#!/bin/sh

# Set these paths appropriately

BIN=/home/lianet/expert/tools/tree-tagger-linux-3.2/bin
CMD=/home/lianet/expert/tools/tree-tagger-linux-3.2/cmd
LIB=/home/lianet/expert/tools/tree-tagger-linux-3.2/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/italian-abbreviations
PARFILE=${LIB}/italian-utf8.par

$TOKENIZER -i -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
