#!/bin/sh

# Set these paths appropriately

BIN=/home/lianet/expert/tools/tree-tagger-linux-3.2/bin
CMD=/home/lianet/expert/tools/tree-tagger-linux-3.2/cmd
LIB=/home/lianet/expert/tools/tree-tagger-linux-3.2/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
