#!/bin/sh

# Set these paths appropriately

BIN=/home/lianet/expert/tools/tree-tagger-linux-3.2/bin
CMD=/home/lianet/expert/tools/tree-tagger-linux-3.2/cmd
LIB=/home/lianet/expert/tools/tree-tagger-linux-3.2/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/swahili-abbreviations
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
